# Generated by Django 5.2.10 on 2026-03-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deals',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
