# Generated by Django 5.2.10 on 2026-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_is_deals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['updated_at']},
        ),
    ]
