# Generated by Django 5.2.10 on 2026-03-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at']},
        ),
    ]
