# Generated by Django 5.2.10 on 2026-02-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_update_at_order_updated_at_and_more'),
        ('products', '0006_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
