# Generated by Django 5.2.10 on 2026-03-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_address_city_alter_address_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_by', to='orders.address'),
        ),
    ]
