# Generated by Django 5.2.10 on 2026-04-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
    ]
